import React from 'react'
import { LevelRange, Unit } from './classes'


export const GameContext = React.createContext<{
    level: LevelRange,
    setLevel: React.Dispatch<React.SetStateAction<LevelRange>>,
    cumulativeLevel: number,
    setCumulativeLevel: React.Dispatch<React.SetStateAction<number>>,
    gold: number,
    setGold: React.Dispatch<React.SetStateAction<number>>,
    champPool: Unit[],
    setChampPool: React.Dispatch<React.SetStateAction<Unit[]>>,
    champShop: (Unit|undefined)[],
    setChampShop: React.Dispatch<React.SetStateAction<(Unit|undefined)[]>>,
    champBench: (Unit|undefined)[],
    setChampBench: React.Dispatch<React.SetStateAction<(Unit|undefined)[]>>,
    gameActive: boolean,
    time: number,
    setTime: React.Dispatch<React.SetStateAction<number>>,
    sellActive: boolean,
    setSellActive: React.Dispatch<React.SetStateAction<boolean>>,
    sellAreaHovered: boolean,
    setSellAreaHovered: React.Dispatch<React.SetStateAction<boolean>>,
    activeTraits: any,
    setActiveTraits: React.Dispatch<React.SetStateAction<any>>,
    gameHistory: any[],
    setGameHistory: React.Dispatch<React.SetStateAction<any>>,
    image1Loaded: boolean,
    setImage1Loaded: React.Dispatch<React.SetStateAction<boolean>>,
    image2Loaded: boolean,
    setImage2Loaded: React.Dispatch<React.SetStateAction<boolean>>,
    image3Loaded: boolean,
    setImage3Loaded: React.Dispatch<React.SetStateAction<boolean>>,
    image4Loaded: boolean,
    setImage4Loaded: React.Dispatch<React.SetStateAction<boolean>>,
    image5Loaded: boolean,
    setImage5Loaded: React.Dispatch<React.SetStateAction<boolean>>
  }>({
    level: 7,
    setLevel: () => {},
    cumulativeLevel: 74,
    setCumulativeLevel: () => {},
    gold: 50,
    setGold: () => {},
    champPool: [],
    setChampPool: () => {},
    champShop: [],
    setChampShop: () => {},
    champBench: [],
    setChampBench: () => {},
    gameActive: false,
    time: 50,
    setTime: () => {},
    sellActive: false,
    setSellActive: () => {},
    sellAreaHovered: false,
    setSellAreaHovered: () => {},
    activeTraits: {},
    setActiveTraits: () => {},
    gameHistory: [],
    setGameHistory: () => {},
    image1Loaded: false,
    setImage1Loaded: () => {},
    image2Loaded: false,
    setImage2Loaded: () => {},
    image3Loaded: false,
    setImage3Loaded: () => {},
    image4Loaded: false,
    setImage4Loaded: () => {},
    image5Loaded: false,
    setImage5Loaded: () => {}
  })